language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 3d1dcf89-2035-4fe9-b681-9ebad93b93bf
  app: aqueous-lowlands-49674
  on:
    repo: anthonypagano/node-shopping-list-integration-tests
