language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: n4a8dLjLPWEJKL5zqHvZFglf78P6SqX31sT0hsD9oLixn+KHBF1XvBRFS4LqZQ3RIJzsE7T3RwOo+5DWqB1VDqkG6ALZIMNizr+pNK/zO3ma7ANOTDhHryByTlnLYWbXbSuwmqXtcRyjjMAfJ7Ii8bHpIx63/p6nq7WE+fVeEDsvLemlfaF8lknc5IAiB+L4p/oIlzHk7ZcIri6ycay8YqNafOmLIJ63wr2c3sdFpdvWBBgXWfX9zxyPIPjDYHw9LLxpQ4Yznw95r68dgRg9ujO1ojGY0W2AX9Lfq/LTYtI+W2MdzQPcuIogZWiI8+zUNkXkanHRfZd8pOGPgjQkRGrhXJ+FPGI3gBCoSXV49H4uUNpLeC2HGgR8RVgRhbdkVfVYI/2cnargBZvEjkLM4qlUx30nl5WPZ1THSMLvLAxE8WBCuXCqUU1KrqM9Qz8lPt2fwH3QRVD2GR2xmwPZgCnc3GIOVlJrly2LTCVltAMMk26Dwbcb3hfCeDm0+6RTaKtCZLE327MdkQLNSp1ssK+uEaE8Q3jkXFGrwIBB98QZw7HW5KKRhh5b5pxVKwP0RF9hbU4btCkKQd1BBnBlMAE8M9ykhsLCx6i6GZ5OEPMmO/6Hawn/F3rR5VqhtmL5Egw3gbtONGFr1CIPGzlJSuRBrtMYevGDI4P9IwrVow0=
  app: ancient-temple-93631
  on:
    repo: anthonypagano/node-shopping-list-integration-tests
